#!/usr/bin/env python3
"""Summarize and plot CA-AFC convergence curves from train.log.

This script reads train.log directly.

Parsing strategy:
1) Prefer "epoch_record=<json>" lines because they are loss-aggregation safe.
2) Fallback to per-batch log lines and aggregate by epoch + split.

Outputs:
- Per-epoch table for key train/valid metrics.
- Curve statistics (min/max/mean/median/last).
- Simple ASCII trend lines for quick terminal inspection.
- Optional PNG plots (loss/rec/emb/ratio/lr) for convergence inspection.
"""

from __future__ import annotations

import argparse
import json
import math
import re
from dataclasses import dataclass
from pathlib import Path
from statistics import mean, median
from typing import Dict, Iterable, List, Optional, Tuple


EPOCH_START_RE = re.compile(r"Epoch\s+(\d+)/(\d+)\s+started:\s+stage=([a-zA-Z0-9_\-]+)")
EPOCH_RECORD_RE = re.compile(r"epoch_record=(\{.*\})")

# Example batch line payload:
# [train] stage=finetune batch=20/1780 ... emb/rec=0.1204 ... grad_emb/rec=0.2413 ...
BATCH_RE = re.compile(
    r"\[(train|valid)\]\s+stage=([a-zA-Z0-9_\-]+)\s+batch=(\d+)/(\d+).*?"
    r"emb/rec=([0-9eE+\-.]+).*?grad_emb/rec=([0-9eE+\-.]+)"
)


@dataclass
class EpochSplitStats:
    loss: float
    rec_loss: float
    emb_loss: float
    smooth_loss: float
    emb_to_rec: float
    grad_emb_to_rec: float


@dataclass
class EpochStats:
    epoch: int
    stage: str
    train: Optional[EpochSplitStats]
    valid: Optional[EpochSplitStats]


@dataclass
class BatchAgg:
    emb_values: List[float]
    grad_values: List[float]

    def __init__(self):
        self.emb_values = []
        self.grad_values = []

    def add(self, emb_to_rec: float, grad_emb_to_rec: float):
        self.emb_values.append(emb_to_rec)
        self.grad_values.append(grad_emb_to_rec)

    def finalize(self) -> Optional[EpochSplitStats]:
        if not self.emb_values:
            return None
        return EpochSplitStats(
            loss=float("nan"),
            rec_loss=float("nan"),
            emb_loss=float("nan"),
            smooth_loss=float("nan"),
            emb_to_rec=float(mean(self.emb_values)),
            grad_emb_to_rec=float(mean(self.grad_values)),
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Summarize per-epoch emb/rec and grad_emb/rec from train.log.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--log",
        type=Path,
        required=True,
        help="Path to train.log generated by my_methods/scripts/train_ca_afc.py",
    )
    parser.add_argument(
        "--split",
        type=str,
        default="train",
        choices=["train", "valid", "both"],
        help="Which split(s) to show in curve summaries.",
    )
    parser.add_argument(
        "--trend_width",
        type=int,
        default=28,
        help="ASCII trend width.",
    )
    parser.add_argument(
        "--json_out",
        type=Path,
        default=None,
        help="Optional output JSON path for downstream plotting.",
    )
    parser.add_argument(
        "--plot_dir",
        type=Path,
        default=None,
        help="Optional output directory for convergence PNG plots.",
    )
    return parser.parse_args()


def _safe_float(value: object, default: float = 0.0) -> float:
    try:
        f = float(value)
        if math.isfinite(f):
            return f
    except (TypeError, ValueError):
        pass
    return default


def _as_stats(split_obj: object) -> Optional[EpochSplitStats]:
    if not isinstance(split_obj, dict):
        return None
    return EpochSplitStats(
        loss=_safe_float(split_obj.get("loss"), 0.0),
        rec_loss=_safe_float(split_obj.get("rec_loss"), 0.0),
        emb_loss=_safe_float(split_obj.get("emb_loss"), 0.0),
        smooth_loss=_safe_float(split_obj.get("smooth_loss"), 0.0),
        emb_to_rec=_safe_float(split_obj.get("emb_to_rec_ratio"), 0.0),
        grad_emb_to_rec=_safe_float(split_obj.get("grad_emb_rec_ratio"), 0.0),
    )


def parse_epoch_records(lines: Iterable[str]) -> List[EpochStats]:
    out: List[EpochStats] = []
    for raw in lines:
        m = EPOCH_RECORD_RE.search(raw)
        if not m:
            continue
        payload = m.group(1)
        try:
            record = json.loads(payload)
        except json.JSONDecodeError:
            continue
        epoch = int(record.get("epoch", 0))
        stage = str(record.get("stage", "unknown"))
        train_stats = _as_stats(record.get("train"))
        valid_stats = _as_stats(record.get("valid"))
        out.append(EpochStats(epoch=epoch, stage=stage, train=train_stats, valid=valid_stats))

    out.sort(key=lambda x: x.epoch)
    return out


def parse_from_batches(lines: Iterable[str]) -> List[EpochStats]:
    # Track current epoch from epoch-start lines.
    epoch_stage: Dict[int, str] = {}
    current_epoch = 0

    # epoch -> split -> agg
    aggs: Dict[int, Dict[str, BatchAgg]] = {}

    for raw in lines:
        m_epoch = EPOCH_START_RE.search(raw)
        if m_epoch:
            current_epoch = int(m_epoch.group(1))
            stage = m_epoch.group(3)
            epoch_stage[current_epoch] = stage
            aggs.setdefault(current_epoch, {"train": BatchAgg(), "valid": BatchAgg()})
            continue

        m_batch = BATCH_RE.search(raw)
        if not m_batch:
            continue
        split = m_batch.group(1)
        stage = m_batch.group(2)
        emb_to_rec = _safe_float(m_batch.group(5), 0.0)
        grad_emb_to_rec = _safe_float(m_batch.group(6), 0.0)

        if current_epoch <= 0:
            # If log was trimmed and no epoch header appears, skip safely.
            continue

        epoch_stage.setdefault(current_epoch, stage)
        aggs.setdefault(current_epoch, {"train": BatchAgg(), "valid": BatchAgg()})
        aggs[current_epoch][split].add(emb_to_rec, grad_emb_to_rec)

    out: List[EpochStats] = []
    for epoch in sorted(aggs.keys()):
        stage = epoch_stage.get(epoch, "unknown")
        train_stats = aggs[epoch]["train"].finalize()
        valid_stats = aggs[epoch]["valid"].finalize()
        out.append(EpochStats(epoch=epoch, stage=stage, train=train_stats, valid=valid_stats))
    return out


def inject_lr_from_epoch_records(rows: List[EpochStats], lines: Iterable[str]) -> Dict[int, float]:
    """Read per-epoch lr from epoch_record timing block when available."""

    lr_by_epoch: Dict[int, float] = {}
    for raw in lines:
        m = EPOCH_RECORD_RE.search(raw)
        if not m:
            continue
        try:
            record = json.loads(m.group(1))
        except json.JSONDecodeError:
            continue
        epoch = int(record.get("epoch", 0))
        timing = record.get("timing", {})
        if isinstance(timing, dict):
            lr_by_epoch[epoch] = _safe_float(timing.get("lr"), 0.0)
    return lr_by_epoch


def _summary(values: List[float]) -> Dict[str, float]:
    if not values:
        return {"min": 0.0, "max": 0.0, "mean": 0.0, "median": 0.0, "last": 0.0}
    return {
        "min": float(min(values)),
        "max": float(max(values)),
        "mean": float(mean(values)),
        "median": float(median(values)),
        "last": float(values[-1]),
    }


def _trend(values: List[float], width: int) -> str:
    if not values:
        return "(empty)"
    if len(values) == 1:
        return "*"

    width = max(8, width)
    if len(values) <= width:
        sampled = values
    else:
        sampled = []
        for i in range(width):
            j = round(i * (len(values) - 1) / (width - 1))
            sampled.append(values[j])

    lo = min(sampled)
    hi = max(sampled)
    if abs(hi - lo) < 1e-12:
        return "-" * len(sampled)

    # 8-level ASCII-safe palette.
    palette = " .:-=+*#"
    chars = []
    for v in sampled:
        t = (v - lo) / (hi - lo)
        idx = int(round(t * (len(palette) - 1)))
        idx = max(0, min(idx, len(palette) - 1))
        chars.append(palette[idx])
    return "".join(chars)


def _collect_series(rows: List[EpochStats], split: str) -> Dict[str, List[float]]:
    series = {
        "epoch": [],
        "loss": [],
        "rec_loss": [],
        "emb_loss": [],
        "smooth_loss": [],
        "emb_to_rec": [],
        "grad_emb_to_rec": [],
    }
    for r in rows:
        stats = r.train if split == "train" else r.valid
        if stats is None:
            continue
        series["epoch"].append(r.epoch)
        series["loss"].append(stats.loss)
        series["rec_loss"].append(stats.rec_loss)
        series["emb_loss"].append(stats.emb_loss)
        series["smooth_loss"].append(stats.smooth_loss)
        series["emb_to_rec"].append(stats.emb_to_rec)
        series["grad_emb_to_rec"].append(stats.grad_emb_to_rec)
    return series


def print_table(rows: List[EpochStats]):
    header = (
        "epoch stage      train_loss train_rec train_emb train_emb/rec train_grad_emb/rec  "
        "valid_loss valid_rec valid_emb valid_emb/rec valid_grad_emb/rec"
    )
    print(header)
    print("-" * len(header))
    for r in rows:
        t_loss = r.train.loss if r.train else float("nan")
        t_rec = r.train.rec_loss if r.train else float("nan")
        t_emb_loss = r.train.emb_loss if r.train else float("nan")
        t_emb_ratio = r.train.emb_to_rec if r.train else float("nan")
        t_grad = r.train.grad_emb_to_rec if r.train else float("nan")
        v_loss = r.valid.loss if r.valid else float("nan")
        v_rec = r.valid.rec_loss if r.valid else float("nan")
        v_emb_loss = r.valid.emb_loss if r.valid else float("nan")
        v_emb_ratio = r.valid.emb_to_rec if r.valid else float("nan")
        v_grad = r.valid.grad_emb_to_rec if r.valid else float("nan")
        print(
            f"{r.epoch:>5d} {r.stage:<10} {t_loss:>10.4f} {t_rec:>9.4f} {t_emb_loss:>9.4f} {t_emb_ratio:>13.4f} {t_grad:>18.4f}"
            f" {v_loss:>10.4f} {v_rec:>9.4f} {v_emb_loss:>9.4f} {v_emb_ratio:>13.4f} {v_grad:>18.4f}"
        )


def print_curve_summary(rows: List[EpochStats], split: str, trend_width: int):
    series = _collect_series(rows, split)
    epochs = series["epoch"]
    if not epochs:
        print(f"[{split}] no data")
        return

    loss_s = _summary(series["loss"])
    rec_s = _summary(series["rec_loss"])
    emb_s = _summary(series["emb_to_rec"])
    grad_s = _summary(series["grad_emb_to_rec"])
    print(f"[{split}] epochs={len(epochs)} range={epochs[0]}..{epochs[-1]}")
    print(
        "  loss        min={min:.4f} max={max:.4f} mean={mean:.4f} median={median:.4f} last={last:.4f}".format(
            **loss_s
        )
    )
    print(
        "  rec_loss    min={min:.4f} max={max:.4f} mean={mean:.4f} median={median:.4f} last={last:.4f}".format(
            **rec_s
        )
    )
    print(
        "  emb/rec     min={min:.4f} max={max:.4f} mean={mean:.4f} median={median:.4f} last={last:.4f}".format(
            **emb_s
        )
    )
    print(
        "  grad_emb/rec min={min:.4f} max={max:.4f} mean={mean:.4f} median={median:.4f} last={last:.4f}".format(
            **grad_s
        )
    )
    print(f"  loss trend         |{_trend(series['loss'], trend_width)}|")
    print(f"  rec_loss trend     |{_trend(series['rec_loss'], trend_width)}|")
    print(f"  emb/rec trend      |{_trend(series['emb_to_rec'], trend_width)}|")
    print(f"  grad_emb/rec trend |{_trend(series['grad_emb_to_rec'], trend_width)}|")


def maybe_plot(rows: List[EpochStats], lr_by_epoch: Dict[int, float], out_dir: Path):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception as exc:
        print(f"plot_warning=matplotlib unavailable, skip plotting: {exc}")
        return

    out_dir.mkdir(parents=True, exist_ok=True)

    train = _collect_series(rows, "train")
    valid = _collect_series(rows, "valid")

    def _plot_pair(ax, key: str, title: str, ylabel: str):
        if train["epoch"]:
            ax.plot(train["epoch"], train[key], marker="o", label="train")
        if valid["epoch"]:
            ax.plot(valid["epoch"], valid[key], marker="s", label="valid")
        ax.set_title(title)
        ax.set_xlabel("epoch")
        ax.set_ylabel(ylabel)
        ax.grid(True, alpha=0.3)
        ax.legend()

    # Figure 1: objective losses
    fig, axes = plt.subplots(2, 2, figsize=(12, 8), constrained_layout=True)
    _plot_pair(axes[0, 0], "loss", "Total Loss", "loss")
    _plot_pair(axes[0, 1], "rec_loss", "Reconstruction Loss", "rec_loss")
    _plot_pair(axes[1, 0], "emb_loss", "Embedding Consistency Loss", "emb_loss")
    _plot_pair(axes[1, 1], "smooth_loss", "Smoothness Loss", "smooth_loss")
    fig.savefig(out_dir / "loss_curves.png", dpi=150)
    plt.close(fig)

    # Figure 2: balancing/gradient ratios
    fig, axes = plt.subplots(1, 2, figsize=(12, 4), constrained_layout=True)
    _plot_pair(axes[0], "emb_to_rec", "emb/rec Ratio", "ratio")
    _plot_pair(axes[1], "grad_emb_to_rec", "grad_emb/rec Ratio", "ratio")
    fig.savefig(out_dir / "ratio_curves.png", dpi=150)
    plt.close(fig)

    # Figure 3: learning rate
    epochs = sorted(lr_by_epoch.keys())
    if epochs:
        lrs = [lr_by_epoch[e] for e in epochs]
        fig, ax = plt.subplots(1, 1, figsize=(8, 4), constrained_layout=True)
        ax.plot(epochs, lrs, marker="o")
        ax.set_title("Learning Rate by Epoch")
        ax.set_xlabel("epoch")
        ax.set_ylabel("lr")
        ax.grid(True, alpha=0.3)
        fig.savefig(out_dir / "lr_curve.png", dpi=150)
        plt.close(fig)

    print(f"saved_plots={out_dir}")


def main():
    args = parse_args()
    log_path: Path = args.log.resolve()
    if not log_path.exists():
        raise FileNotFoundError(f"log file not found: {log_path}")

    lines = log_path.read_text(encoding="utf-8", errors="replace").splitlines()

    rows = parse_epoch_records(lines)
    parser_used = "epoch_record"
    if not rows:
        rows = parse_from_batches(lines)
        parser_used = "batch_fallback"

    if not rows:
        raise RuntimeError("No parsable epoch data found in log.")

    lr_by_epoch = inject_lr_from_epoch_records(rows, lines)

    print(f"log={log_path}")
    print(f"parsed_epochs={len(rows)} parser={parser_used}")
    print_table(rows)
    print()

    if args.split in ("train", "both"):
        print_curve_summary(rows, split="train", trend_width=args.trend_width)
    if args.split in ("valid", "both"):
        print_curve_summary(rows, split="valid", trend_width=args.trend_width)

    if args.plot_dir is not None:
        maybe_plot(rows, lr_by_epoch=lr_by_epoch, out_dir=args.plot_dir)

    if args.json_out is not None:
        payload = {
            "log": str(log_path),
            "parser": parser_used,
            "epochs": [
                {
                    "epoch": r.epoch,
                    "stage": r.stage,
                    "train": {
                        "loss": r.train.loss if r.train else None,
                        "rec_loss": r.train.rec_loss if r.train else None,
                        "emb_loss": r.train.emb_loss if r.train else None,
                        "smooth_loss": r.train.smooth_loss if r.train else None,
                        "emb_to_rec": r.train.emb_to_rec if r.train else None,
                        "grad_emb_to_rec": r.train.grad_emb_to_rec if r.train else None,
                    },
                    "valid": {
                        "loss": r.valid.loss if r.valid else None,
                        "rec_loss": r.valid.rec_loss if r.valid else None,
                        "emb_loss": r.valid.emb_loss if r.valid else None,
                        "smooth_loss": r.valid.smooth_loss if r.valid else None,
                        "emb_to_rec": r.valid.emb_to_rec if r.valid else None,
                        "grad_emb_to_rec": r.valid.grad_emb_to_rec if r.valid else None,
                    },
                }
                for r in rows
            ],
        }
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"saved_json={args.json_out}")


if __name__ == "__main__":
    main()
